# Generated by Django 3.0.8 on 2021-12-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20211224_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='sd',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='sd_volume_max',
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='main_cam_mp',
            field=models.CharField(max_length=255, verbose_name='Оcновна камера'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='ram',
            field=models.CharField(max_length=255, verbose_name="Об'єм вбудованої пам'яті"),
        ),
    ]
